apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080 # Change to desired NodePort value
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443 # Change to desired NodePort value
