apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green-deployment
  labels:
    app: frontend
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      color: green
  template:
    metadata:
      labels:
        app: frontend
        color: green
    spec:
      containers:
      - name: frontend
        image: docker.io/dinesh10275/dev-frontend:v1.0
        ports:
        - containerPort: 80
