apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: green-frontend
  namespace: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      color: green
  template:
    metadata:
      labels:
        app: frontend
        color: green
    spec:
      containers:
      - name: frontend
        image: docker.io/dinesh10275/dev-frontend:v2.0  # Assuming v2.0 is the new version
        ports:
        - containerPort: 80
        # Add livenessProbe and readinessProbe if needed
  strategy:
    blueGreen:
      activeService: frontend-green
      previewService: frontend-blue
