apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-bluegreen
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: bluegreen-active
      previewService: bluegreen-preview
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: docker.io/dinesh10275/dev-frontend:v1.0.1
        ports:
        - containerPort: 80
