apiVersion: v1
kind: Service
metadata:
  name: frontend-green
  namespace: argo-rollouts
spec:
  selector:
    app: frontend
    color: green  # Match the labels with the pods it selects
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: frontend
    color: green
