apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: argo-rollouts
spec:
  selector:
    app: frontend
    color: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort  # Specify the service type as NodePort
