apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: argo-rollouts
spec:
  selector:
    app: frontend
    color: blue  # Match labels with the blue version
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

