apiVersion: v1
kind: Service
metadata:
  name: frontend-green
  namespace: argo-rollouts
spec:
  selector:
    app: frontend
    color: green  # Match labels with the green version
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
