apiVersion: v1
kind: Service
metadata:
  name: frontend-green
  namespace: argo-rollouts
spec:
  selector:
    app: frontend
    color: green  # Make sure this label matches the label in the Rollout spec
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
