apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: argo-rollouts
spec:
  selector:
    app: frontend
    color: blue  # Match the labels with the pods it selects
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
