apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: kastenk10
  name: k10
  namespace: kasten-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k10
  template:
    metadata:
      labels:
        app: k10
    spec:
      containers:
        - image: 'kastenhq/k10:v6.5.6'
          name: k10
          ports:
            - containerPort: 8080
