apiVersion: apps/v1
kind: Deployment
metadata:
  name: k10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k10
  template:
    metadata:
      labels:
        app: k10
    spec:
      containers:
      - name: k10
        image: kastenhq/k10:v6.5.6
        ports:
        - containerPort: 8080
