apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: kastenk10
  name: k10
  namespace: kasten-io
spec:
  ports:
    - nodePort: 30005
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: k10
  type: NodePort

