apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
spec:
  replicas: 1 # adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      containers:
      - name: nginx-proxy-manager
        image: jc21/nginx-proxy-manager:latest
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 443
        volumeMounts:
        - name: data
          mountPath: /data
        - name: letsencrypt
          mountPath: /etc/letsencrypt
      volumes:
      - name: data
        hostPath:
          path: /srv/dockerdata/NGINXproxymanager/data
      - name: letsencrypt
        hostPath:
          path: /srv/dockerdata/NGINXproxymanager/letsencrypt
