apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  namespace: thetym
spec:
  type: ClusterIP
  selector:
    app: nginx-proxy-manager
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dashboard
      protocol: TCP
      port: 81
      targetPort: 81
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443



