apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-poxy-manager
  name: nginx-proxy-manager
  namespace: your-namespace
spec:
  ports:
    - nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
    - nodePort: 30081
      port: 81
      protocol: TCP
      targetPort: 81
    - nodePort: 30443
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: nginx-proxy-manager
  type: NodePort


