apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  namespace: your-namespace  # Replace 'your-namespace' with your desired namespace name
spec:
  type: NodePort
  selector:
    app: nginx-proxy-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30081
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443

