apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
      - name: frontend1
        image: dinesh10275/dev-frontend:beta1
        ports:
        - containerPort: 80
        
