apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/ramesh10654/myapp:v1.3
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"  # Request 64 Megabytes of memory
            cpu: "250m"      # Request 250 milliCPU (0.25 CPU)
          limits:
            memory: "128Mi"  # Limit to 128 Megabytes of memory
            cpu: "500m"      # Limit to 500 milliCPU (0.5 CPU)

---
# Modified Service YAML with namespace
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: thetym   # Specify the namespace here
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000   # You can specify a nodePort here or let Kubernetes assign one automatically
  selector:
    app: frontend
