apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscaler
  namespace: thetym
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1   # Minimum number of replicas
  maxReplicas: 2   # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 25
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 25  # Adjust as needed

