apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: atlassian/jira-software:latest
        ports:
        - containerPort: 8080
        env:
          - name: JIRA_DATABASE_URL
           
