apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: atlassian/jira-software:latest
        ports:
        - containerPort: 8080
        - name: SPRING_DATA_MONGODB_URI
              value: "mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/betanew1?retryWrites=true&w=majority"
           
