apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-endpoints-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: thetym
roleRef:
  kind: ClusterRole
  name: list-endpoints
  apiGroup: rbac.authorization.k8s.io
