apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      volumes:   # Define the volume here
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: portainer
        image: portainer/portainer-ce:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: docker-socket   # Reference the volume here
          mountPath: /var/run/docker.sock
