apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: thetym
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9003
    nodePort: 32000  # Specify a nodePort within the allowed range
  selector:
    app: portainer
