apiVersion: v1
kind: Service
metadata:
  name: portainer
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30000  # Specify a nodePort within the allowed range
  selector:
    app: portainer
