apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: thetym
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ramesh10654/thetymbackend:v1.2
        ports:
        - containerPort: 80  # Add the container port if your backend service listens on a specific port
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://dbadmin:bbs2020@ec2-13-233-100-218.ap-south-1.compute.amazonaws.com:37011,ec2-13-233-100-218.ap-south-1.compute.amazonaws.com:37022,ec2-13-233-100-218.ap-south-1.compute.amazonaws.com:37033/Thetymv2?replicaSet=ReplSet1&authSource=admin&connectTimeoutMS=300000"
        imagePullPolicy: IfNotPresent  # Specify the image pull policy if needed
        imagePullSecrets:
        - name: dockerhub-secret
