apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: thetym
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dinesh10275/dev-backend:v1
        ports:
        - containerPort: 80  # Add the container port if your backend service listens on a specific port
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/betatest?retryWrites=true&w=majority
        imagePullPolicy: IfNotPresent  # Specify the image pull policy if needed
        imagePullSecrets:
        - name: dockerhub-secret
