apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: thetym-backend
  name: backend
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ramesh10654/thetymbackend:v1.1
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/testdb?retryWrites=true&w=majority
          imagePullPolicy: IfNotPresent
          resources: {}
          imagePullSecrets:
            - name: dockerhub-secret
