apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: thetym
  labels:
    app: backend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1
        image: dinesh10275/dev-backend:v1
        ports:
        - containerPort: 80
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/betatest?retryWrites=true&w=majority
