apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: thetym-backend
  name: backend
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ramesh10654/thetymbackend:v1.1
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb+srv://dbadmin:bbs2020@13.233.253.109:37011,13.233.253.109:37022,13.233.253.109:37033/Thetymv2?replicaSet=ReplSet1&authSource=admin
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: dockerhub-secret
