apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend1
    app.kubernetes.io/instance: backend1
  name: backend1
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: >-
               mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/betatest?retryWrites=true&w=majority
          image: dinesh10275/dev-backend:beta1
          name: backend1
          ports:
            - containerPort: 80
