apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: thetym  # Add the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ramesh10654/thetymbackend:v1.1
      imagePullSecrets:
      - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: thetym
spec:
  type: LoadBalancer  # Use LoadBalancer type
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: backend
