apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: thetym-backend
  name: backend
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ramesh10654/thetymbackend:v1.1
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://dbadmin:bbs2020@ip-172-31-5-87.ap-south-1.compute.internal:37011,ip-172-31-5-87.ap-south-1.compute.internal:37022,ip-172-31-5-87.ap-south-1.compute.internal:37033/Thetymv2?replicaSet=ReplSet1&authSource=admin
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: dockerhub-secret
