apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: thetym-backend
  name: backend
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: >-
                mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/testdb?retryWrites=true&w=majority
          image: 'ramesh10654/thetymbackend:v1.1'
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: dockerhub-secret
          name: backend
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: thetym
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31000
  selector:
    app: backend
