apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/basic-auth
stringData:
  username: ramesh10654  # required field for kubernetes.io/basic-auth
  password: dckr_pat_z7Q3hn0q6JL5rJPusr5SZY5LHss # required field for kubernetes.io/basic-auth
