
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: thetym
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJyYW1lc2gxMDY1NCIsCiAgICAgICJwYXNzd29yZCI6ICJkY2tyX3BhdF96N1EzaG4wcTZKTDVySlB1c3I1U1pZNUxIc3MiLAogICAgICAiZW1haWwiOiAicmFtZXNoQHRoZXR5bS5jb20iLAogICAgICAiYXV0aCI6ICIiCiAgICB9CiAgfQp9Cgo="
        }
      }
    }
