apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    chart: {{ include "backend-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: {{ .Values.backend.mongodb.uri }}
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: dockerhub-secret
