apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: backend
